import AddTask from "@/Componants/AddTask";
import TaskCard from "@/Componants/TaskCard";
import { createTask } from "@/Lib/actions";
import { getTasks } from "@/Lib/task";
import { Button } from "@heroui/react";
import Link from "next/link";

export const metadata = {
  title: 'Task Page',
  description: 'Generated by create next app',
}
const TasksPage = async () => {
  const tasks = await getTasks();
  return (
    <div className="p-8">
      <h2 className="text-center text-4xl">
        Tasks Page:<span className="text-red-500">{tasks.length}</span>
      </h2>
      <div className="text-center p-5 space-x-5">
        <AddTask createTask={createTask}></AddTask>
<Link href="/Task/New">
<Button variant="secondary">Add New Task</Button>
</Link>

      </div>


      <div className=" grid grid-cols-3 gap-5 justify-center">
        {tasks.map((task)=><TaskCard key={task.id} task={task}>

        </TaskCard>)}
      </div>
    </div>
  );
};

export default TasksPage;
